### ISSUE TITLE
the error of quantization of upsampling layer from caffe model 

### ISSUE THREAD

**Issue by xtanitfy** [khadas/khadas_docs#247]
D Acuity output shape(upsample): (1 22 40 256)
-----------len(input_tensor): 1
0---(1, 11, 20, 256)
Traceback (most recent call last):
  File "tensorzonex.py", line 446, in <module>
  File "tensorzonex.py", line 383, in main
  File "acuitylib/app/tensorzone/workspace.py", line 198, in run
  File "acuitylib/app/tensorzone/workspace.py", line 172, in _setup_graph
  File "acuitylib/app/tensorzone/graph.py", line 59, in generate
  File "acuitylib/acuitynetbuilder.py", line 274, in build
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 301, in build_layer
  File "acuitylib/acuitynetbuilder.py", line 331, in build_layer
  File "acuitylib/layer/acuitylayer.py", line 280, in compute_tensor
  File "../../bin/client/upsample.py", line 85, in compute_out_tensor
    idx = input_tensor[1]
IndexError: list index out of range
[15524] Failed to execute script tensorzonex

**Comment by xtanitfy** [comment]
I think I can sove the problem by building the array of input index.
