### ISSUE TITLE
generate nb file error

### ISSUE THREAD

**Issue by xtanitfy** [khadas/khadas_docs#248]
ERROR log as follow:
mv: cannot stat '/disk4/MLOGIC/aml_npu_sdk_6.4.0.10/acuity-toolkit/convert_caffe/modle1/*.nb': No such file or directory
mv: cannot stat '/disk4/MLOGIC/aml_npu_sdk_6.4.0.10/acuity-toolkit/convert_caffe/modle1/*.dat': No such file or directory
Traceback (most recent call last):
  File "ovxgenerator.py", line 195, in <module>
  File "ovxgenerator.py", line 186, in main
  File "acuitylib/app/exporter/ovxlib_case/casegenerator.py", line 470, in generate
  File "acuitylib/app/exporter/ovxlib_case/casegenerator.py", line 444, in _gen_special_case
  File "acuitylib/app/exporter/ovxlib_case/casegenerator.py", line 388, in _gen_nb_file
AttributeError: 'CaseGenerator' object has no attribute 'nbg_graph_file_path'
[32170] Failed to execute script ovxgenerator

**Comment by xtanitfy** [comment]
问题又出在不支持upsample laye，问题又回到 #247 上，我把upsample改成tf.image.nearest_neighbor，应该该op不能被支持导致gen_nbg 毫无症状崩溃，这个信息没有被提示出来，只能一层一层的卡，才卡到的

**Comment by xtanitfy** [comment]
搞定，要改成Upsampling
